[package]
name = "rust-fun"
version = "0.1.0"
authors = ["rgutmann <ralph.gutmann@t-systems.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
num-format = "0.4.0"
